# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title multivariate regression
#' @name mvn_continuous
#' @export
NULL

#' @title testing binary
#' @name mvn_binary
#' @export
NULL

mvn_continuous <- function(Y, X, delta, epsilon, iter) {
    .Call('_BGGM_mvn_continuous', PACKAGE = 'BGGM', Y, X, delta, epsilon, iter)
}

trunc_mvn <- function(mu, rinv, z, y, cutpoints) {
    .Call('_BGGM_trunc_mvn', PACKAGE = 'BGGM', mu, rinv, z, y, cutpoints)
}

mvn_binary <- function(Y, X, delta, epsilon, iter, beta_prior, cutpoints) {
    .Call('_BGGM_mvn_binary', PACKAGE = 'BGGM', Y, X, delta, epsilon, iter, beta_prior, cutpoints)
}

