# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Theta_continuous <- function(Y, iter, delta, epsilon, prior_only, explore) {
    .Call(`_BGGM_Theta_continuous`, Y, iter, delta, epsilon, prior_only, explore)
}

mv_continuous <- function(Y, X, delta, epsilon, iter) {
    .Call(`_BGGM_mv_continuous`, Y, X, delta, epsilon, iter)
}

trunc_mvn <- function(mu, rinv, z, y, cutpoints) {
    .Call(`_BGGM_trunc_mvn`, mu, rinv, z, y, cutpoints)
}

mv_binary <- function(Y, X, delta, epsilon, iter, beta_prior, cutpoints) {
    .Call(`_BGGM_mv_binary`, Y, X, delta, epsilon, iter, beta_prior, cutpoints)
}

Sigma_i_not_i <- function(x, index) {
    .Call(`_BGGM_Sigma_i_not_i`, x, index)
}

select_col <- function(x, index) {
    .Call(`_BGGM_select_col`, x, index)
}

select_row <- function(x, index) {
    .Call(`_BGGM_select_row`, x, index)
}

remove_row <- function(x, which) {
    .Call(`_BGGM_remove_row`, x, which)
}

remove_col <- function(x, index) {
    .Call(`_BGGM_remove_col`, x, index)
}

mv_ordinal_cowles <- function(Y, X, delta, epsilon, iter, MH) {
    .Call(`_BGGM_mv_ordinal_cowles`, Y, X, delta, epsilon, iter, MH)
}

mv_ordinal_albert <- function(Y, X, iter, delta, epsilon, K) {
    .Call(`_BGGM_mv_ordinal_albert`, Y, X, iter, delta, epsilon, K)
}

copula <- function(z0_start, levels, K, Sigma_start, iter, delta, epsilon, idx) {
    .Call(`_BGGM_copula`, z0_start, levels, K, Sigma_start, iter, delta, epsilon, idx)
}

